:development:
  site_name: Fikus
  tagline: Development Environment
  max_cache_time: 600
:test:
  site_name: Fikus
  tagline: Test Environment
  max_cache_time: 172800
:production:
  site_name: Fikus
  tagline: The Simple Ruby CMS
  max_cache_time: 172800  